import { DBErrorCode } from "./db-error.enum.js";

export const DBErrorStatusMap: Record<DBErrorCode, number> = {
  DUPLICATE_RESOURCE: 409,
  FOREIGN_KEY_VIOLATION: 400,
  NOT_NULL_VIOLATION: 400,
  CHECK_CONSTRAINT_VIOLATION: 400,
  INTEGRITY_CONSTRAINT_VIOLATION: 400,

  INVALID_INPUT_SYNTAX: 400,
  DATA_EXCEPTION: 400,

  SERIALIZATION_FAILURE: 409,
  DEADLOCK_DETECTED: 409,
  TRANSACTION_ROLLBACK: 409,

  INVALID_AUTHORIZATION: 401,

  SYNTAX_ERROR: 400,

  INSUFFICIENT_RESOURCES: 503,
  OPERATOR_INTERVENTION: 503,
  SYSTEM_ERROR: 500,

  RESOURCE_NOT_FOUND: 404,
  DATABASE_ERROR: 500,
};
